#ifndef MID_CC_HPP
#define MID_CC_HPP

///MIDI Continuous Controllers
enum MidiController : unsigned char {
    CC_BANK_SELECT_C                    = 0,
    CC_MODULATION_WHEEL_C,
    CC_BREATH_CONTROLLER_C,
    CC_FOOT_PEDAL_C                     = 4,
    CC_PORTAMENTO_TIME_C,
    CC_DATA_ENTRY_C,
    CC_CHANNEL_VOLUME_C,
    CC_BALANCE_C,
    CC_PAN_C                            = 10,
    CC_EXPRESSION_C,
    CC_EFFECT_CONTROLLER_0_C,
    CC_EFFECT_CONTROLLER_1_C,
    CC_GENERAL_PURPOSE_0_C              = 16,
    CC_GENERAL_PURPOSE_1_C,
    CC_GENERAL_PURPOSE_2_C,
    CC_GENERAL_PURPOSE_3_C,
    CC_BANK_SELECT_F                    = 32,
    CC_MODULATION_WHEEL_F,
    CC_BREATH_CONTROLLER_F,
    CC_FOOT_PEDAL_F                     = 36,
    CC_PORTAMENTO_TIME_F,
    CC_DATA_ENTRY_F,
    CC_CHANNEL_VOLUME_F,
    CC_BALANCE_F,
    CC_PAN_F                            = 42,
    CC_EXPRESSION_F,
    CC_EFFECT_CONTROLLER_0_F,
    CC_EFFECT_CONTROLLER_1_F,
    CC_HOLD_PEDAL_0                     = 64,
    CC_PORTAMENTO_PEDAL,
    CC_SOSTENUTO_PEDAL,
    CC_SOFT_PEDAL,
    CC_LEGATO_PEDAL,
    CC_HOLD_PEDAL_1,
    CC_SOUND_CONTROLLER_VARIATION,
    CC_SOUND_CONTROLLER_TIMBRE,
    CC_SOUND_CONTROLLER_RELEASE_TIME,
    CC_SOUND_CONTROLLER_ATTACK_TIME,
    CC_SOUND_CONTROLLER_BRIGHTNESS,
    CC_SOUND_CONTROLLER_DECAY_TIME,
    CC_SOUND_CONTROLLER_VIBRATO_RATE,
    CC_SOUND_CONTROLLER_VIBRATO_DEPTH,
    CC_SOUND_CONTROLLER_VIBRATO_DELAY,
    CC_SOUND_CONTROLLER_UNDEFINED,
    CC_GENERAL_PURPOSE_4,
    CC_GENERAL_PURPOSE_5,
    CC_GENERAL_PURPOSE_6,
    CC_GENERAL_PURPOSE_7,
    CC_PORTAMENTO_CONTROLLER,
    CC_VELOCITY_EXTENSION               = 88,
    CC_EFFECT_DEPTH_0_REVERB            = 91,
    CC_EFFECT_DEPTH_1_TEMOLO_DEPTH,
    CC_EFFECT_DEPTH_2_CHORUS_DEPTH,
    CC_EFFECT_DEPTH_3_CELESTE_DEPTH,
    CC_EFFECT_DEPTH_4_PHASER,
    CC_DATA_INCREMENT,
    CC_DATA_DECREMENT,
    CC_NONREGISTERED_PARAMETER_C,
    CC_NONREGISTERED_PARAMETER_F,
    CC_REGISTERED_PARAMETER_C,
    CC_REGISTERED_PARAMETER_F,
    CC_RESET_SOUND                      = 120,
    CC_RESET_CONTROLLERS,
    CC_LOCAL_CONTROL_SWITCH,
    CC_RESET_NOTES,
    CC_OMNI_OFF,
    CC_OMNI_ON,
    CC_MONOPHONIC_MODE,
    CC_POLYPHONIC_MODE,
};

///MIDI Custom Continuous Controller values
enum MidiCustomController : unsigned char {
    //PSX-style loops
    CC_PSX_LOOP             = 0x63,
    //PSX-style loop values
    CC_PSX_LOOPSTART        = 0x14,
    CC_PSX_LOOPEND          = 0x1E,

    //XML-style loops
    CC_XML_LOOPSTART        = 0x74,
    CC_XML_LOOPEND          = 0x75,
    //XML-style loop values
    CC_XML_LOOPINFINITE     = 0x00,
    CC_XML_LOOPRESERVED     = 0x7F,

    //EMIDI-style loops
    CC_EMD_LOOPSTART        = 0x76,
    CC_EMD_LOOPEND          = 0x77,
};


#endif
